### ISSUE TITLE
Does this work for .mp4 URLs ??

### ISSUE THREAD

**Issue by FaridHaddad** [neekeetab/CachingPlayerItem#2]

**Comment by neekeetab** [comment]
Well, I haven't tested it with video files but I don't see any reason why it wouldn't work. Keep in mind though, that all cached data is stored completely in RAM and returned to you as NSData object, so I don't recommend playing large video files (>100Mb).

**Comment by FaridHaddad** [comment]
Okay thank you so much, but this would be cached for how long ?
Can it last for a week for ex ?

**Comment by neekeetab** [comment]
As I said, you will be given NSData object upon successfull download. You are responsible for what to do with it next.

**Comment by FaridHaddad** [comment]
i know, but i meant the cache will stay for how long ? the data will stay cached for how long ? forever ?

**Comment by neekeetab** [comment]
CachingPlayerItem doesn't have internal cache. All it does is gives you ability to store downloaded resource by yourself.

**Comment by FaridHaddad** [comment]
I don't understand .. how it caches ?

**Comment by neekeetab** [comment]
Technically, it doesn't cache. It only loads the data and gives it to you.
