### ISSUE TITLE
How can I specify custom headers? init(asset: AVAsset) not implemented

### ISSUE THREAD

**Issue by fadizant** [neekeetab/CachingPlayerItem#20]
how can I use AVAsset with this control, I have to use AVAsset in order to add header to my URL
advice please.

**Comment by neekeetab** [comment]
You can avoid using init(asset: AVAsset) if you just want to add custom headers. What you can do instead is to change ResourceLoaderDelegate's startDataRequest(with:) method and provide the necessary headers to the dataTask.
