### ISSUE TITLE
Determine when end is reached, play complete?

### ISSUE THREAD

**Issue by smhk** [neekeetab/CachingPlayerItem#26]
Regarding playback complete,

the amazing `CachingPlayerItemDelegate` does not have a "playback has reached end" concept

CachingPlayerItem is incredible - is there an easy way to add a "playback complete" concept?

With "old" style code, we use something like

```
        NotificationCenter.default.addObserver(
        	self,
        	selector: #selector(fileComplete),
        	name: NSNotification.Name.AVPlayerItemDidPlayToEndTime,
        	object: nil)
```

Is there a better way when using the amazing `CachingPlayerItem` ?  Thanks

**Comment by neekeetab** [comment]
CachingPlayerItem is essentially AVPlayerItem but with a custom loader, so determining the end of the playback is the same as for AVPlayerItem

**Comment by smhk** [comment]
OK!  Done, thanks!  Fantastic lib.
