### ISSUE TITLE
How to clear the cached memory? 

### ISSUE THREAD

**Issue by auro-krishna** [neekeetab/CachingPlayerItem#31]
I want to clear all the allocated memory at some point in time. How can I achieve this?

**Comment by ealeksandrov** [comment]
Please check https://github.com/neekeetab/CachingPlayerItem/issues/29#issuecomment-578122754 and https://github.com/neekeetab/CachingPlayerItem/issues/10.

`CachingPlayerItem` only gives convenient delegate access to player data, it doesn't do any of saving/caching/reusing.
