### ISSUE TITLE
App crashes at processPendingRequests() from didReceive()

### ISSUE THREAD

**Issue by mohamedrafi-rapid** [neekeetab/CachingPlayerItem#46]
Thread 126: "-[__NSTaggedDate count]: unrecognized selector sent to instance 0x8000000000000000"

Please help @neekeetab

**Comment by mohamedrafi-rapid** [comment]
Resolved the issue by cancelAndInvalidate the playeritem session

**Comment by mohamedrafi-rapid** [comment]
@neekeetab 
Now I am cancelling download an ongoing session by playerItem?.resourceLoaderDelegate.session?.invalidateAndCancel(). Made resourceLoaderDelegate.session public. 

Will this cause the crash? Actually crash happens very rarely. To reduce crash rate In processPendingRequests() I have added a main async now

**Comment by Samigos** [comment]
> @neekeetab Now I am cancelling download an ongoing session by playerItem?.resourceLoaderDelegate.session?.invalidateAndCancel(). Made resourceLoaderDelegate.session public.
> 
> Will this cause the crash? Actually crash happens very rarely. To reduce crash rate In processPendingRequests() I have added a main async now

Can you please show how? I have the exact issue, but to me it happens a lot!
