### ISSUE TITLE
player.play() not working

### ISSUE THREAD

**Issue by Whotan** [neekeetab/CachingPlayerItem#5]
The player is not playing at all, however the file is downloaded completely.

**Comment by neekeetab** [comment]
Hi! Sorry for a late response. I haven't been able to reproduce what you described, but my guess is that you don't keep a strong reference to the AVPlayer. If it doesn't help, please feel free to provide your code. We'll figure that out.

**Comment by Whotan** [comment]
Hi!

**Comment by Whotan** [comment]
Hi! nope, I keep a strong reference to the AVPlayer. Here is my code: class MusicPlayer: CachingPlayerItemDelegate {
    
    static let sharedInstance = MusicPlayer()
  
    public var showing : Bool = false
    public var playing : Bool = false
    public var playList = songsGetAPI()
    public var index : Int = 0
    var player : AVPlayer!
    public var remainingTime = "00:00"
    public var tabBar: MusicPlayerBar?
    
    private init() {
        print("Music player initialized.")
    }
    
    func play(_playlist: songsGetAPI, _index : Int ) {
        self.playList = _playlist
        self.index = _index
        self.showing = true
        
        tabBar?.showPlayer(songName: (playList.results[index]?.name)!)
        self.remainingTime = "00:00"
        self.tabBar?.updateLabel(remaining: "00:00", didReachEnd: false)
        
        guard let url = URL(string :(playList.results[index]?.file_url)!) else {
            print("url creating failed : " + (playList.results[index]?.file_url)!)
            return
        }
        
        do {
            try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback)
            try AVAudioSession.sharedInstance().setActive(true)
//            let playerItem = AVPlayerItem(url: url)
            let playerItem = CachingPlayerItem(url: url)
            playerItem.delegate = self
//            NotificationCenter.default.addObserver(self, selector: #selector(playerItemDidPlayToEndTime), name: NSNotification.Name.AVPlayerItemDidPlayToEndTime, object: playerItem)

            player = AVPlayer(playerItem:playerItem)
            player.automaticallyWaitsToMinimizeStalling = false
            player.play()
            self.playing = true
            
            let interval = CMTime(seconds: 0.5, preferredTimescale: CMTimeScale(NSEC_PER_SEC))
            self.player.addPeriodicTimeObserver(forInterval: interval, queue: DispatchQueue.main , using: {
            elapsedTime in
                if self.playing{
                    self.remainingTime = elapsedTime.durationText
                    self.tabBar?.updateLabel(remaining: self.remainingTime, didReachEnd: false)
                }else{self.tabBar?.updateLabel(remaining: "00:00", didReachEnd: true)}
            })
        }catch{
            self.playing = false
            print(error)
            print("music player failed")
        }
    }

**Comment by neekeetab** [comment]
I've just run your code and for me everything seems fine. Make sure that a url that you're trying to play ends with a file extension, e.g. ".mp3". Also make sure that the file located by the url is valid and can be played at all. Hope it helps.

**Comment by Whotan** [comment]
Thanks for your response, unfortunately the url does not end with extention, what should I do about it?

**Comment by neekeetab** [comment]
Appending file extension to each resource on the backend will work. If you don't have access to the server or use 3rd party APIs, you can use the same technique as i did -- construct a fake url to feed to AVPlayer and then when it asks you to load the resource, intercept the url and reconstruct the real one, then download using URLSession. You can achieve it with a little bit of customization of CachingPlayerItem.

**Comment by Whotan** [comment]
I tried to add an extension where the scheme changes and generates a fake url, but still not working. I changed the extension to this: fileprivate extension URL {
    
    func withScheme(_ scheme: String) -> URL? {
        var components = URLComponents(url: self, resolvingAgainstBaseURL: false)
        components?.scheme = scheme
        let newURL = URL(string: (components?.url?.absoluteString)! + ".mp3")
        return newURL!
    }
    
}

**Comment by Whotan** [comment]
Works fine, thank you so much

**Comment by neekeetab** [comment]
You're welcome!

**Comment by NicholasFLee** [comment]
Sorry for comment in this closed-issue,I've encountered the same problem and I can't understand this answer you provided, could you explain more detail? or maybe some code will be great :D .

**Comment by neekeetab** [comment]
Whotan had an issue with urls that don't end with file extension not being played. The reason for this is  that AVPlayerItem determines the type of the file to play from the file's url extension. That said, no url extension -- no playback. But there's a workaround -- we can provide a fake url to AVPlayerItem with a proper extension (like mp3 for an audio file) but then substitute the data requested in AVAssetResourceLoaderDelegate with the data loaded from the actual url (the one without extension). I don't have the code, but Whotan may.
