### ISSUE TITLE
Issue Playing my mp3 file from url

### ISSUE THREAD

**Issue by RajMohan143** [neekeetab/CachingPlayerItem#6]
I am only change the url. But file not playing.
let strUrl = (arrCardData.object(at: tag)as!NSMutableDictionary).value(forKey: "voice")!
        let url = URL(string: strUrl as! String)!
        let playerItem = CachingPlayerItem(url: url)
        playerItem.delegate = self
        player = AVPlayer(playerItem: playerItem)
        player.automaticallyWaitsToMinimizeStalling = false
        player.play()

Delegate method showing data downloads
and url file is playing on browser well.

**Comment by neekeetab** [comment]
Do your urls contain file extension, e.g. ".mp3"?

**Comment by RajMohan143** [comment]
Yes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by RajMohan143** [comment]
The same file is playing in android. Mobile

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by neekeetab** [comment]
Please, provide a link to a sample file so I can check it for myself. Along with the code ideally.

**Comment by pkhodaveissi** [comment]
Hey @neekeetab 
didn't want to open a new issue so here it goes
I try to use your code as you documented:
```
let playerItem = CachingPlayerItem(url: url, customFileExtension: "mp3")
```
but still not working, is there any other setting I should apply?

great lib btw, thanks for your work

**Comment by pkhodaveissi** [comment]
This is the url:
``` 
https://drive.google.com/uc?export=download&id=1AjPwylDJgR8DOnmJWeRgZzjsohi-7ekj
```
I can play this using `AVPlayerItem` but no chance using `CachingPlayerItem`

I can't help with steps cuz the project is somehow complicated, when testing with normal urls (*.mp3) everything's back to normal though

**Comment by neekeetab** [comment]
I can confirm that the playback won't start. I've noticed that the url redirects to another one with the actual file. But even with that url it won't play. I think the issue lies somewhere in the http header that comes with the request. 

I don't know if you're restricted by using google drive. But I know people have used firebase storage and it worked fine with it. Just saying.

**Comment by pkhodaveissi** [comment]
tnx man, good to know

**Comment by neekeetab** [comment]
I will take a deeper look at the issue with google drive links when I have more time. Please share your solution if you manage to get around this.

**Comment by pkhodaveissi** [comment]
Well It's not a priority for me right now but will do happily whenever it
becomes one
